### PR TITLE
feat: added flakes

### PR DESCRIPTION
**Pull request by prithvihv**

### CODE REVIEW

**Comment by prithvihv** [comment]
@davidak i run into https://github.com/tweag/trustix/issues/42 when trying to build it, how did you resolve this?

**Comment by prithvihv** [comment]
@davidak  do we need to update the python package lock files?

**Comment by davidak** [comment]
> how did you resolve this?

see https://github.com/tweag/trustix/issues/42#issuecomment-1120505705

**Comment by prithvihv** [comment]
@davidak that doesn't build using `poetry2nix.mkPoetryApplication`. That command puts you into a shell where you run npm run build.

I think the make command doesn't build anything python. I'm confused on what I'm supposed to be packaging

**Comment by davidak** [comment]
The two commands should work:

```
[davidak@gaming:~/code/trustix/packages/trustix-nix-reprod]$ nix-shell --run 'make build'
[davidak@gaming:~/code/trustix/packages/trustix-nix-reprod]$ nix-shell --run 'make develop'
```

what is the issue you get?

**Pull request closed without merging**
